version: '3.9'

services:
  api:
    build:
      context: ./api
    ports:
      - "8000:8000"
    volumes:
      - ./fpt:/app/fpt

  dashboard:
    build:
      context: ./dashboard
    ports:
      - "8501:8501"
    volumes:
      - ./fpt:/app/fpt
