version: "3.9"

services:
  api:
    build:
      context: ./api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./fpt:/app/fpt
    environment:
      - PYTHONPATH=/app
    restart: unless-stopped

  dashboard:
    build:
      context: ./dashboard
    ports:
      - "8501:8501"
    volumes:
      - .:/app
      - ./fpt:/app/fpt
    environment:
      - API_URL=http://api:8000
    depends_on:
      - api
    restart: unless-stopped