name: Daily Scraper Run

on:
  schedule:
    # Runs every day at 2:00 AM UTC, adjust as needed
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  run-scraper-and-loader:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13.1'  # Use your preferred Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper script (download CSV)
        run: python src/scraper/scrape.py

      - name: Run data loader script (load to DB)
        run: python src/loader/load_to_db.py

      - name: Upload downloaded raw CSV
        uses: actions/upload-artifact@v4
        with:
          name: raw-wfp-food-prices-csv
          path: data/raw/wfpvam_foodprices.csv  # Path where scrape.py saves the CSV
